services:
  kafka:
    container_name: kafka
    hostname: localhost
    image: bitnami/kafka:latest
    networks:
      - kafka-network
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./kafka_cluster/kafka_data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka-network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./kafka_cluster/zookeeper_data:/bitnami/zookeeper
networks:
  kafka-network:
    driver: bridge
